import { HardhatRuntimeEnvironment } from "hardhat/types";
import { DeployFunction } from "hardhat-deploy/types";
import fs from "fs";
import path from "path";

const deployShieldFi: DeployFunction = async function (hre: HardhatRuntimeEnvironment) {
  const { deployer } = await hre.getNamedAccounts();
  const { deploy } = hre.deployments;

  console.log(`\n🛡️  Deploying ShieldFi to ${hre.network.name}...`);
  console.log(`   Deployer: ${deployer}`);

  const shieldFi = await deploy("ShieldFi", {
    from: deployer,
    args: [],
    log: true,
    autoMine: true,
  });

  console.log(`\n✅ ShieldFi deployed at: ${shieldFi.address}`);
  console.log(`   Network: ${hre.network.name} (chainId: ${hre.network.config.chainId})`);

  // Write the deployed address to the frontend constants file
  const constantsDir = path.join(__dirname, "../../packages/nextjs/app");
  const constantsPath = path.join(constantsDir, "constants.ts");

  const abiPath = path.join(__dirname, "../artifacts/contracts/ShieldFi.sol/ShieldFi.json");

  // Write constants.ts with deployed address
  const constantsContent = `// Auto-generated by deploy script — do not edit manually
export const SHIELDFI_ADDRESS = "${shieldFi.address}" as const;
export const CHAIN_ID = ${hre.network.config.chainId ?? 11155111};
export const NETWORK_NAME = "${hre.network.name}";
`;

  if (fs.existsSync(constantsDir)) {
    fs.writeFileSync(constantsPath, constantsContent);
    console.log(`   Wrote constants.ts → ${constantsPath}`);
  }

  // Also write to frontend src folder (react-vite artifact)
  const frontendConstantsDir = path.join(__dirname, "../../../artifacts/shieldfi/src");
  const frontendConstantsPath = path.join(frontendConstantsDir, "constants.ts");

  if (fs.existsSync(frontendConstantsDir)) {
    fs.writeFileSync(frontendConstantsPath, constantsContent);
    console.log(`   Wrote constants.ts → ${frontendConstantsPath}`);
  }

  // Copy ABI
  if (fs.existsSync(abiPath)) {
    const abi = JSON.parse(fs.readFileSync(abiPath, "utf8"));

    const abiDestDir = path.join(frontendConstantsDir, "abi");
    if (!fs.existsSync(abiDestDir)) fs.mkdirSync(abiDestDir, { recursive: true });

    const abiDestPath = path.join(abiDestDir, "ShieldFi.json");
    fs.writeFileSync(abiDestPath, JSON.stringify(abi.abi, null, 2));
    console.log(`   Copied ABI → ${abiDestPath}`);
  }

  if (hre.network.name !== "hardhat" && hre.network.name !== "localhost") {
    console.log(`\n🔍 Verify on Etherscan:`);
    console.log(`   npx hardhat verify --network ${hre.network.name} ${shieldFi.address}`);
  }
};

export default deployShieldFi;
deployShieldFi.tags = ["ShieldFi"];
