/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface ShieldFiInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "acceptBid"
      | "approveInvoice"
      | "confidentialProtocolId"
      | "createInvoice"
      | "financingBids"
      | "getBidders"
      | "getInvoiceMetadata"
      | "getMyInvoiceAmount"
      | "invoiceCounter"
      | "invoices"
      | "owner"
      | "regulatorDecrypt"
      | "renounceOwnership"
      | "submitFinancingBid"
      | "transferOwnership"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "BidSubmitted"
      | "InvoiceApproved"
      | "InvoiceCreated"
      | "InvoiceFinanced"
      | "OwnershipTransferred"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "acceptBid",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "approveInvoice",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "confidentialProtocolId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "createInvoice",
    values: [AddressLike, BytesLike, BytesLike, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "financingBids",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getBidders",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getInvoiceMetadata",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getMyInvoiceAmount",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "invoiceCounter",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "invoices",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "regulatorDecrypt",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "submitFinancingBid",
    values: [BigNumberish, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(functionFragment: "acceptBid", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "approveInvoice",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "confidentialProtocolId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createInvoice",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "financingBids",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getBidders", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getInvoiceMetadata",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getMyInvoiceAmount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "invoiceCounter",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "invoices", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "regulatorDecrypt",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "submitFinancingBid",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
}

export namespace BidSubmittedEvent {
  export type InputTuple = [invoiceId: BigNumberish, financier: AddressLike];
  export type OutputTuple = [invoiceId: bigint, financier: string];
  export interface OutputObject {
    invoiceId: bigint;
    financier: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace InvoiceApprovedEvent {
  export type InputTuple = [invoiceId: BigNumberish, buyer: AddressLike];
  export type OutputTuple = [invoiceId: bigint, buyer: string];
  export interface OutputObject {
    invoiceId: bigint;
    buyer: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace InvoiceCreatedEvent {
  export type InputTuple = [
    invoiceId: BigNumberish,
    supplier: AddressLike,
    buyer: AddressLike
  ];
  export type OutputTuple = [
    invoiceId: bigint,
    supplier: string,
    buyer: string
  ];
  export interface OutputObject {
    invoiceId: bigint;
    supplier: string;
    buyer: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace InvoiceFinancedEvent {
  export type InputTuple = [invoiceId: BigNumberish, financier: AddressLike];
  export type OutputTuple = [invoiceId: bigint, financier: string];
  export interface OutputObject {
    invoiceId: bigint;
    financier: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface ShieldFi extends BaseContract {
  connect(runner?: ContractRunner | null): ShieldFi;
  waitForDeployment(): Promise<this>;

  interface: ShieldFiInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  acceptBid: TypedContractMethod<
    [invoiceId: BigNumberish, financier: AddressLike],
    [void],
    "nonpayable"
  >;

  approveInvoice: TypedContractMethod<
    [invoiceId: BigNumberish],
    [void],
    "nonpayable"
  >;

  confidentialProtocolId: TypedContractMethod<[], [bigint], "view">;

  createInvoice: TypedContractMethod<
    [
      buyer: AddressLike,
      inputAmount: BytesLike,
      inputProof: BytesLike,
      inputDueDate: BytesLike,
      dueDateProof: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  financingBids: TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [string],
    "view"
  >;

  getBidders: TypedContractMethod<
    [invoiceId: BigNumberish],
    [string[]],
    "view"
  >;

  getInvoiceMetadata: TypedContractMethod<
    [invoiceId: BigNumberish],
    [
      [string, string, boolean, boolean, string] & {
        supplier: string;
        buyer: string;
        buyerApproved: boolean;
        financed: boolean;
        financier: string;
      }
    ],
    "view"
  >;

  getMyInvoiceAmount: TypedContractMethod<
    [invoiceId: BigNumberish],
    [string],
    "view"
  >;

  invoiceCounter: TypedContractMethod<[], [bigint], "view">;

  invoices: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        bigint,
        string,
        string,
        string,
        string,
        boolean,
        boolean,
        string,
        string
      ] & {
        invoiceId: bigint;
        supplier: string;
        buyer: string;
        encryptedAmount: string;
        encryptedDueDate: string;
        buyerApproved: boolean;
        financed: boolean;
        financier: string;
        encryptedFinancingRate: string;
      }
    ],
    "view"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  regulatorDecrypt: TypedContractMethod<
    [invoiceId: BigNumberish],
    [string],
    "nonpayable"
  >;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  submitFinancingBid: TypedContractMethod<
    [invoiceId: BigNumberish, inputRate: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "acceptBid"
  ): TypedContractMethod<
    [invoiceId: BigNumberish, financier: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "approveInvoice"
  ): TypedContractMethod<[invoiceId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "confidentialProtocolId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "createInvoice"
  ): TypedContractMethod<
    [
      buyer: AddressLike,
      inputAmount: BytesLike,
      inputProof: BytesLike,
      inputDueDate: BytesLike,
      dueDateProof: BytesLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "financingBids"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "getBidders"
  ): TypedContractMethod<[invoiceId: BigNumberish], [string[]], "view">;
  getFunction(
    nameOrSignature: "getInvoiceMetadata"
  ): TypedContractMethod<
    [invoiceId: BigNumberish],
    [
      [string, string, boolean, boolean, string] & {
        supplier: string;
        buyer: string;
        buyerApproved: boolean;
        financed: boolean;
        financier: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getMyInvoiceAmount"
  ): TypedContractMethod<[invoiceId: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "invoiceCounter"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "invoices"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        bigint,
        string,
        string,
        string,
        string,
        boolean,
        boolean,
        string,
        string
      ] & {
        invoiceId: bigint;
        supplier: string;
        buyer: string;
        encryptedAmount: string;
        encryptedDueDate: string;
        buyerApproved: boolean;
        financed: boolean;
        financier: string;
        encryptedFinancingRate: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "regulatorDecrypt"
  ): TypedContractMethod<[invoiceId: BigNumberish], [string], "nonpayable">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "submitFinancingBid"
  ): TypedContractMethod<
    [invoiceId: BigNumberish, inputRate: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;

  getEvent(
    key: "BidSubmitted"
  ): TypedContractEvent<
    BidSubmittedEvent.InputTuple,
    BidSubmittedEvent.OutputTuple,
    BidSubmittedEvent.OutputObject
  >;
  getEvent(
    key: "InvoiceApproved"
  ): TypedContractEvent<
    InvoiceApprovedEvent.InputTuple,
    InvoiceApprovedEvent.OutputTuple,
    InvoiceApprovedEvent.OutputObject
  >;
  getEvent(
    key: "InvoiceCreated"
  ): TypedContractEvent<
    InvoiceCreatedEvent.InputTuple,
    InvoiceCreatedEvent.OutputTuple,
    InvoiceCreatedEvent.OutputObject
  >;
  getEvent(
    key: "InvoiceFinanced"
  ): TypedContractEvent<
    InvoiceFinancedEvent.InputTuple,
    InvoiceFinancedEvent.OutputTuple,
    InvoiceFinancedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;

  filters: {
    "BidSubmitted(uint256,address)": TypedContractEvent<
      BidSubmittedEvent.InputTuple,
      BidSubmittedEvent.OutputTuple,
      BidSubmittedEvent.OutputObject
    >;
    BidSubmitted: TypedContractEvent<
      BidSubmittedEvent.InputTuple,
      BidSubmittedEvent.OutputTuple,
      BidSubmittedEvent.OutputObject
    >;

    "InvoiceApproved(uint256,address)": TypedContractEvent<
      InvoiceApprovedEvent.InputTuple,
      InvoiceApprovedEvent.OutputTuple,
      InvoiceApprovedEvent.OutputObject
    >;
    InvoiceApproved: TypedContractEvent<
      InvoiceApprovedEvent.InputTuple,
      InvoiceApprovedEvent.OutputTuple,
      InvoiceApprovedEvent.OutputObject
    >;

    "InvoiceCreated(uint256,address,address)": TypedContractEvent<
      InvoiceCreatedEvent.InputTuple,
      InvoiceCreatedEvent.OutputTuple,
      InvoiceCreatedEvent.OutputObject
    >;
    InvoiceCreated: TypedContractEvent<
      InvoiceCreatedEvent.InputTuple,
      InvoiceCreatedEvent.OutputTuple,
      InvoiceCreatedEvent.OutputObject
    >;

    "InvoiceFinanced(uint256,address)": TypedContractEvent<
      InvoiceFinancedEvent.InputTuple,
      InvoiceFinancedEvent.OutputTuple,
      InvoiceFinancedEvent.OutputObject
    >;
    InvoiceFinanced: TypedContractEvent<
      InvoiceFinancedEvent.InputTuple,
      InvoiceFinancedEvent.OutputTuple,
      InvoiceFinancedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
  };
}
